### ISSUE TITLE
Button Overlapping with search bar

### ISSUE THREAD

**Issue by jitesh-sidhani** [Mikeexe2/Internet-radio-stream-links#1]
Can you assign me this issue?
After searching , Google button overlaps with the search bar. I would also like to improve the styling.
![image](https://github.com/Mikeexe2/Internet-radio-stream-links/assets/110370070/944b6607-9f04-422d-b89f-1131f85177d9)

**Comment by Mikeexe2** [comment]
hi there! I have updated the code for the search function. You can try redesign the style, and put it in pull request or email sasalele-team@basic.pp.ua
